apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: production-bookinfo
  namespace: fluxprod-bookinfo
spec:
  interval: 1m
  url: https://github.com/shamusx/congenial-journey
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-bookinfo
  namespace: fluxprod-bookinfo
spec:
  interval: 5m
  path: ./fluxcd-demo/app/bookinfo
  sourceRef:
    kind: GitRepository
    name: production-bookinfo