# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sleep
resources:
- namespace.yaml
- https://raw.githubusercontent.com/istio/istio/master/samples/sleep/sleep.yaml